version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: productrateplanservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P4ssword!
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5433:5432"
    networks:
      - db-network
    restart: always

  app:
    build: .
    container_name: productrateplanservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/productrateplanservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P4ssword!
      - SPRING_CACHE_TYPE=simple
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
    depends_on:
      - postgres
    networks:
      - db-network
    restart: always

networks:
  db-network:
    driver: bridge